# Generated by Django 5.1.2 on 2024-10-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='unit_number',
            field=models.IntegerField(),
        ),
    ]
